### ISSUE TITLE
The checking of extended_key_usage shouldn't be mandatory

### ISSUE THREAD

**Issue by lsun100** [DMTF/libspdm#1592] opened 2023-01-06 18:15 UTC
Currently the code seems checking extended_key_usage and requires that it exists, which seems not necessary according to the latest spec.

https://github.com/DMTF/libspdm/blob/702be53a73bd1cf962bf89ede58a16607e289a1b/library/spdm_crypt_lib/libspdm_crypt_cert.c#L822-L828

**Comment by steven-bellock** [comment] 2023-01-06 18:26
At one time the SPDM specification required "extended key usage" instead of "key usage". See https://github.com/DMTF/SPDM-WG/issues/993 This was fixed in 1.1.1, so this is probably a holdover from that.

**Comment by jyao1** [comment] 2023-01-07 02:23
Agree. EKU should not be checked as mandatory.

I think the problem is that EKU should be checked if it is present.
I will file another issue to add conditional check.

**Closed** 2023-01-07 02:29 UTC
Labels: bug
